version: '3'
services:
  app:
    build: app
    environment:
      HOST: "0.0.0.0"
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
    networks:
      local:
        ipv4_address: 192.168.20.2
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'
    volumes:
      - ./app:/usr/local/src

    command: ["/bin/bash", "/usr/local/src/entrypoint.sh"]
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_ROOT_PASSWORD"
      MYSQL_DATABASE: "MYSQL_DATABASE"
    volumes:
      - "./data/mysql:/var/lib/mysql"
    networks:
      local:
        ipv4_address: 192.168.20.3
  redis:
    image: redis
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: "PMA_USER"
      PMA_PASSWORD: "PMA_PASSWORD"
    depends_on:
      - db
    networks:
      local:
        ipv4_address: 192.168.20.4
    ports:
      - '3030:80'

networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/16
